(function(){
'use strict';

const V06_VERSION='0.6.0';
const DAILY_PAYLOAD=globalThis.MN_DAILY_MATCH||{categories:{},questions:[]};
const DAILY_BY_ID=new Map((DAILY_PAYLOAD.questions||[]).map(question=>[question.id,question]));
const DAILY_PERIODS=['7','14','30','all'];
const GAME_APPS=[
  {id:'wave',short:'Fala',art:'≈',tone:'violet',mini:'1–10'},
  {id:'know',short:'Znasz mnie',art:'?',tone:'rose',mini:'A B C'},
  {id:'who',short:'Kto bardziej',art:'↔',tone:'blue',mini:'TY / JA'},
  {id:'dilemma',short:'Wybór',art:'◇',tone:'amber',mini:'A · B'},
  {id:'scale',short:'Skala',art:'10',tone:'cyan',mini:'1—10'},
  {id:'plan',short:'Plan',art:'!',tone:'red',mini:'TAK?'},
  {id:'words',short:'Słowa',art:'#',tone:'indigo',mini:'3 HASŁA'},
  {id:'story',short:'Historia',art:'⌛',tone:'gold',mini:'MY'},
  {id:'tell',short:'Rozmowa',art:'…',tone:'teal',mini:'POWIEDZ'},
  {id:'challenge',short:'Wyzwania',art:'+',tone:'green',mini:'ZRÓB'},
];
const PACK_HUB=[
  {id:'firstDate',icon:'✦',title:'Pierwsza randka',text:'Lekko i bez zbyt osobistych pytań.'},
  {id:'longTogether',icon:'∞',title:'Długo razem',text:'Rytuały, wspomnienia i wspólna codzienność.'},
  {id:'laugh',icon:'☺',title:'Dużo śmiechu',text:'Absurdalne wybory i lekkie wyzwania.'},
  {id:'travel',icon:'⌁',title:'Podróże',text:'Wyjazdy, kierunki i wakacyjne dylematy.'},
  {id:'future',icon:'→',title:'Plany na przyszłość',text:'Decyzje, marzenia i wspólne cele.'},
  {id:'romantic',icon:'♡',title:'Romantyczny wieczór',text:'Bliskość i spokojny czas we dwoje.'},
  {id:'deep',icon:'◌',title:'Głębsza rozmowa',text:'Potrzeby, granice i wartości.'},
  {id:'reconnect',icon:'↻',title:'Po spięciu',text:'Spokojny powrót do kontaktu.'},
  {id:'weekend',icon:'☼',title:'Weekendowy reset',text:'Odpoczynek, spontaniczność i wspólny czas.'},
  {id:'challenges',icon:'+',title:'Tylko wyzwania',text:'Mniej rozmowy, więcej działania.'},
];

function localDateKey(date=new Date()){
  const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');
  return`${y}-${m}-${d}`;
}
function dateFromKey(key){const[y,m,d]=String(key).split('-').map(Number);return new Date(y,m-1,d,12)}
function hashString(value=''){let hash=2166136261;for(let i=0;i<value.length;i++){hash^=value.charCodeAt(i);hash=Math.imul(hash,16777619)}return hash>>>0}
function seededShuffle(items,seedValue){const copy=[...items];let seed=hashString(String(seedValue))||1;const random=()=>{seed+=0x6D2B79F5;let value=seed;value=Math.imul(value^(value>>>15),value|1);value^=value+Math.imul(value^(value>>>7),value|61);return((value^(value>>>14))>>>0)/4294967296};for(let i=copy.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function daysSinceEpoch(key){const[y,m,d]=String(key).split('-').map(Number);return Math.floor(Date.UTC(y,m-1,d)/86400000)}
function dailyDefinition(key=localDateKey()){
  const categories=Object.keys(DAILY_PAYLOAD.categories||{});if(!categories.length)return{date:key,category:'',questionIds:[]};
  const day=daysSinceEpoch(key),category=categories[((day%categories.length)+categories.length)%categories.length];
  const pool=(DAILY_PAYLOAD.questions||[]).filter(question=>question.category===category),ordered=seededShuffle(pool,`mn-daily-${category}`),occurrence=Math.floor(day/categories.length),start=((occurrence*5)%ordered.length+ordered.length)%ordered.length;
  const selected=[];for(let offset=0;offset<Math.min(5,ordered.length);offset++)selected.push(ordered[(start+offset)%ordered.length]);
  return{date:key,category,questionIds:selected.map(question=>question.id)};
}
function questionCompatibility(question,left,right){left=Number(left);right=Number(right);if(left===right)return 100;if(question?.kind==='scale')return Math.max(0,100-Math.abs(left-right)*34);if(question?.kind==='groups'){const groups=question.groups||[];return groups[left]!==undefined&&groups[left]===groups[right]?60:0}return 0}
function compatibilityLabel(value){if(value===100)return'Myślicie tak samo';if(value>=60)return'Podobne podejście';if(value>0)return'Bliskie, ale inne';return'Inne spojrzenia'}
function compatibilityClass(value){if(value===100)return'exact';if(value>=60)return'near';if(value>0)return'partial';return'different'}
function scoreLabel(score){if(score>=85)return['Bardzo mocne połączenie','Dzisiaj wyjątkowo często wybieraliście podobny kierunek.'];if(score>=65)return['Dużo wspólnego','Macie wiele podobnych priorytetów, a różnice są dobrym tematem do rozmowy.'];if(score>=45)return['Ciekawa mieszanka','Część odpowiedzi was łączy, a część pokazuje dwa różne sposoby patrzenia.'];return['Dwa różne spojrzenia','Różnice nie oznaczają niedopasowania — pokazują, czego możecie się o sobie dowiedzieć.']}
function questionList(state){return(state?.questionIds||[]).map(id=>DAILY_BY_ID.get(id)).filter(Boolean)}
function ensureDailyProfile(){
  if(!profile.dailyCompatibility||typeof profile.dailyCompatibility!=='object')profile.dailyCompatibility={};
  if(!profile.dailyCompatibility.days||typeof profile.dailyCompatibility.days!=='object')profile.dailyCompatibility.days={};
  if(!DAILY_PERIODS.includes(String(profile.dailyCompatibility.period)))profile.dailyCompatibility.period='14';
  return profile.dailyCompatibility;
}
function getDailyState(key=localDateKey(),create=true){
  const daily=ensureDailyProfile();let state=daily.days[key];
  if(!state&&create){const definition=dailyDefinition(key);state={version:1,date:key,category:definition.category,questionIds:definition.questionIds,phase:'intro',player:0,index:0,answers:[[],[]],startedAt:null,finishedAt:null,score:null,results:[]};daily.days[key]=state;saveProfile()}
  return state||null;
}
function completedEntries(){return Object.values(ensureDailyProfile().days).filter(entry=>entry&&Number.isFinite(entry.score)&&entry.finishedAt).sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
function dailyStatsFor(period='all'){
  const all=completedEntries(),limit=period==='all'?Infinity:Number(period)||14,cutoff=new Date();cutoff.setHours(0,0,0,0);if(limit!==Infinity)cutoff.setDate(cutoff.getDate()-limit+1);
  const entries=all.filter(entry=>limit===Infinity||dateFromKey(entry.date)>=cutoff);const average=entries.length?Math.round(entries.reduce((sum,entry)=>sum+entry.score,0)/entries.length):0;const buckets={};for(const entry of entries){const bucket=buckets[entry.category]||{sum:0,count:0};bucket.sum+=entry.score;bucket.count++;buckets[entry.category]=bucket}const categoryAverages=Object.fromEntries(Object.entries(buckets).map(([id,b])=>[id,Math.round(b.sum/b.count)]));return{entries,average,categoryAverages,total:all.length}
}
function dailyStreak(){const completed=new Set(completedEntries().map(entry=>entry.date));let current=0,cursor=new Date();cursor.setHours(12,0,0,0);if(!completed.has(localDateKey(cursor)))cursor.setDate(cursor.getDate()-1);while(completed.has(localDateKey(cursor))){current++;cursor.setDate(cursor.getDate()-1)}let best=0,run=0,previous=null;for(const key of[...completed].sort()){if(!previous)run=1;else{const next=dateFromKey(previous);next.setDate(next.getDate()+1);run=localDateKey(next)===key?run+1:1}best=Math.max(best,run);previous=key}return{current,best}}
function formatDailyDate(key,short=false){return new Intl.DateTimeFormat('pl-PL',short?{day:'numeric',month:'short'}:{weekday:'long',day:'numeric',month:'long'}).format(dateFromKey(key))}
function categoryMeta(id){return DAILY_PAYLOAD.categories?.[id]||{label:id||'Codzienne Dopasowanie',icon:'♡',accent:'#d946ef'}}
function dailyProgress(state){if(!state)return 0;if(state.finishedAt)return 10;return(state.answers?.[0]?.length||0)+(state.answers?.[1]?.length||0)}

function appTile(appData){const count=getAllCards().filter(card=>card.mode===appData.id).length;return`<button class="desktop-app" data-tone="${appData.tone}" onclick="openGameInfo('${appData.id}')" aria-label="Otwórz grę ${escapeHtml(appData.short)}"><span class="desktop-app-icon"><span class="desktop-app-mini">${escapeHtml(appData.mini)}</span><strong>${escapeHtml(appData.art)}</strong><i></i><b></b></span><span class="desktop-app-name">${escapeHtml(appData.short)}</span><small>${count} kart</small></button>`}
function utilityTile(icon,title,subtitle,action,tone='neutral',badge=''){return`<button class="utility-app" data-tone="${tone}" onclick="${action}"><span class="utility-icon">${icon}${badge?`<b>${escapeHtml(badge)}</b>`:''}</span><span><strong>${escapeHtml(title)}</strong><small>${escapeHtml(subtitle)}</small></span></button>`}

renderHome=function(){
  ensureDailyProfile();const stats=calculateStats(),state=getDailyState(),meta=categoryMeta(state.category),streak=dailyStreak(),progress=dailyProgress(state),done=Boolean(state.finishedAt),dateText=new Intl.DateTimeFormat('pl-PL',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
  app.innerHTML=`<section class="desktop-home"><div class="desktop-welcome"><div><span class="eyebrow">MIĘDZY NAMI • v${V06_VERSION}</span><h1>Cześć, ${escapeHtml(settings.names[0])} i ${escapeHtml(settings.names[1])}</h1><p>${escapeHtml(dateText.charAt(0).toUpperCase()+dateText.slice(1))} · wasza prywatna przestrzeń do grania i rozmowy.</p></div><div class="desktop-streak"><span>🔥</span><strong>${streak.current}</strong><small>dni serii</small></div></div>${currentSession?`<div class="resume-banner desktop-resume"><div><strong>Niedokończona sesja</strong><p>${escapeHtml(modeMeta(currentSession.mode).title)} • runda ${currentSession.index+1}/${currentSession.deck.length}</p></div><button class="button good small-button" onclick="resumeSession()">Kontynuuj</button></div>`:''}<button class="daily-launch-card ${done?'complete':''}" onclick="openDailyMatch()" style="--daily-accent:${meta.accent}"><span class="daily-launch-icon">${meta.icon}<i>5</i></span><span class="daily-launch-copy"><small>DZISIEJSZE DOPASOWANIE · ${escapeHtml(meta.label)}</small><strong>${done?`${state.score}% dopasowania`:'5 pytań dla was obojga'}</strong><span>${done?'Wynik jest zapisany do końca dnia. Kliknij, aby porównać odpowiedzi.':progress?`Ukończono ${progress}/10 odpowiedzi — kontynuujcie.`:'Każde odpowiada osobno. Odpowiedzi odkryją się dopiero na końcu.'}</span></span><span class="daily-launch-action">${done?'Wynik →':progress?'Kontynuuj →':'Zacznij →'}</span></button><div class="desktop-section-title"><div><h2>Gry</h2><p>Kliknij ikonę, tak jak aplikację na telefonie.</p></div><button onclick="showPackHub()">Pakiety →</button></div><section class="desktop-app-grid">${GAME_APPS.map(appTile).join('')}</section><div class="desktop-section-title"><div><h2>Dla was</h2><p>Historia, ustawienia i szybkie skróty.</p></div></div><section class="utility-grid">${utilityTile('⚡','Szybka gra','10 losowych kart',"startQuick('quick')",'amber')}${utilityTile('✦','Własna sesja','Połącz wybrane gry',"openMixSetup()",'violet')}${utilityTile('◫','Pakiety','Gotowe zestawy',"showPackHub()",'blue')}${utilityTile('▥','Statystyki',`${stats.sessions} sesji · ${dailyStatsFor('all').total} testów`,"showStats()",'green')}${utilityTile('♥','Ulubione',`${profile.favorites.length} zapisanych kart`,"showFavorites()",'rose')}${utilityTile('⚙','Ustawienia','Profil i dane lokalne',"showSettings()",'neutral')}</section><p class="desktop-privacy">🔒 Wszystkie odpowiedzi i wyniki są obecnie zapisane wyłącznie na tym urządzeniu.</p></section>`;
};

function openDailyMatch(){const state=getDailyState();if(state.finishedAt)ui.view='daily-summary';else if(state.phase==='p1'||state.phase==='p2')ui.view='daily-play';else if(state.phase==='handoff')ui.view='daily-handoff';else ui.view='daily-intro';ui.modal=null;render()}
function startDailyMatch(){const state=getDailyState();if(!state.startedAt)state.startedAt=Date.now();if(state.answers[0].length>=5){state.phase='handoff';state.player=1;state.index=0;ui.view='daily-handoff'}else{state.phase='p1';state.player=0;state.index=Math.min(state.answers[0].length,4);ui.view='daily-play'}saveProfile();render()}
function renderDailyIntro(){const state=getDailyState(),meta=categoryMeta(state.category),stats=dailyStatsFor('14'),streak=dailyStreak();app.innerHTML=`<section class="panel daily-panel" style="--daily-accent:${meta.accent}"><div class="top-row"><button class="back-button" onclick="goHome()">← Pulpit</button><span class="chip">${meta.icon} ${escapeHtml(meta.label)}</span></div><div class="daily-intro-hero"><span class="daily-big-icon">${meta.icon}</span><span class="eyebrow">CODZIENNE DOPASOWANIE</span><h1>Jak dziś myślicie?</h1><p>Pięć tych samych pytań. Najpierw odpowiada ${escapeHtml(settings.names[0])}, potem ${escapeHtml(settings.names[1])}. Nie podglądajcie odpowiedzi — odkryjecie je razem na końcu.</p></div><div class="daily-rule-grid"><div><b>1</b><strong>Odpowiedzi osobno</strong><span>Każda osoba wybiera A, B, C lub D.</span></div><div><b>2</b><strong>Bez podglądania</strong><span>Po pięciu pytaniach przekazujecie telefon.</span></div><div><b>3</b><strong>Wspólny wynik</strong><span>Dostajecie procent i porównanie odpowiedzi.</span></div></div><div class="daily-preview-stats"><span><strong>${stats.average||'—'}${stats.entries.length?'%':''}</strong>średnia 14 dni</span><span><strong>${streak.current}</strong>obecna seria</span><span><strong>${completedEntries().length}</strong>ukończone dni</span></div><button class="button primary full daily-primary" onclick="startDailyMatch()">${dailyProgress(state)?'Kontynuuj dzisiejszy test':'Zaczyna '+escapeHtml(settings.names[0])}</button><button class="button tertiary full" onclick="showDailyStats()">Zobacz historię dopasowania</button></section>`}
function renderDailyPlay(){const state=getDailyState(),questions=questionList(state),question=questions[state.index];if(!question){goHome();return}const meta=categoryMeta(state.category),name=escapeHtml(settings.names[state.player]||`Osoba ${state.player+1}`),selected=state.answers[state.player][state.index];app.innerHTML=`<section class="panel daily-panel daily-question-panel" style="--daily-accent:${meta.accent}"><div class="daily-session-head"><button class="back-button" onclick="dailyExit()">← Wyjdź</button><span>${state.player===0?'Pierwsza osoba':'Druga osoba'} · ${state.index+1}/5</span><span class="chip">${meta.icon} ${escapeHtml(meta.label)}</span></div><div class="daily-progress"><i style="width:${((state.index+1)/5)*100}%"></i></div><div class="daily-player-pill"><span>${state.player===0?'1':'2'}</span><div><small>TERAZ ODPOWIADA</small><strong>${name}</strong></div></div><h2 class="daily-question">${escapeHtml(question.prompt)}</h2><div class="daily-answer-list">${question.answers.map((answer,index)=>`<button class="daily-answer ${selected===index?'selected':''}" onclick="dailyChoose(${index})"><b>${String.fromCharCode(65+index)}</b><span>${escapeHtml(answer)}</span></button>`).join('')}</div>${state.index>0?`<button class="text-button daily-previous" onclick="dailyPrevious()">← Wróć do poprzedniego pytania</button>`:''}<p class="daily-secret-note">🔒 Odpowiedzi ${state.player===0?escapeHtml(settings.names[1]):escapeHtml(settings.names[0])} pozostają ukryte.</p></section>`}
function dailyChoose(index){const state=getDailyState();state.answers[state.player][state.index]=Number(index);if(state.index<4){state.index++;saveProfile();render();return}if(state.player===0){state.phase='handoff';state.player=1;state.index=0;ui.view='daily-handoff';saveProfile();vibrate([20,30,20]);render();return}finalizeDaily(state)}
function dailyPrevious(){const state=getDailyState();if(state.index>0){state.index--;saveProfile();render()}}
function dailyExit(){saveProfile();goHome();toast('Postęp dzisiejszego testu zapisany.')}
function renderDailyHandoff(){const state=getDailyState(),meta=categoryMeta(state.category);app.innerHTML=`<section class="panel daily-panel" style="--daily-accent:${meta.accent}"><div class="top-row"><button class="back-button" onclick="dailyExit()">← Wyjdź</button><span class="chip">5/10 odpowiedzi</span></div><div class="daily-handoff"><span class="handoff-phone">▯<i>•••</i></span><span class="eyebrow">PIERWSZA CZĘŚĆ GOTOWA</span><h1>Przekaż telefon</h1><p>${escapeHtml(settings.names[0])} ma już zapisane odpowiedzi. Teraz ten sam zestaw wypełnia <strong>${escapeHtml(settings.names[1])}</strong>. Nic z pierwszej części nie będzie widoczne.</p><button class="button primary full daily-primary" onclick="dailyAcceptHandoff()">Mam telefon — zaczynam</button><button class="button tertiary full" onclick="dailyExit()">Dokończymy później</button></div></section>`}
function dailyAcceptHandoff(){const state=getDailyState();state.phase='p2';state.player=1;state.index=Math.min(state.answers[1].length,4);ui.view='daily-play';saveProfile();render()}
function finalizeDaily(state){const questions=questionList(state);state.results=questions.map((question,index)=>({questionId:question.id,leftAnswer:state.answers[0][index],rightAnswer:state.answers[1][index],compatibility:questionCompatibility(question,state.answers[0][index],state.answers[1][index])}));state.score=Math.round(state.results.reduce((sum,result)=>sum+result.compatibility,0)/Math.max(1,state.results.length));state.finishedAt=Date.now();state.phase='summary';state.player=1;state.index=4;saveProfile();ui.view='daily-summary';vibrate([30,40,30]);burst();render()}
function renderDailySummary(){const state=getDailyState();if(!state.finishedAt){openDailyMatch();return}const questions=questionList(state),meta=categoryMeta(state.category),[headline,description]=scoreLabel(state.score),streak=dailyStreak();app.innerHTML=`<section class="panel wide daily-panel" style="--daily-accent:${meta.accent}"><div class="top-row"><button class="back-button" onclick="goHome()">← Pulpit</button><span class="chip">${escapeHtml(formatDailyDate(state.date))}</span></div><div class="daily-result-hero"><div class="compatibility-ring" style="--score:${state.score}"><span><strong>${state.score}%</strong><small>dopasowania</small></span></div><div><span class="eyebrow">${meta.icon} ${escapeHtml(meta.label)}</span><h1>${escapeHtml(headline)}</h1><p>${escapeHtml(description)}</p><div class="daily-result-chips"><span>🔥 seria ${streak.current} dni</span><span>✓ 5 pytań</span><span>🔒 zapis lokalny</span></div></div></div><h2 class="daily-answer-heading">Porównanie odpowiedzi</h2><div class="daily-result-list">${questions.map((question,index)=>{const result=state.results[index],left=question.answers[result.leftAnswer],right=question.answers[result.rightAnswer],cls=compatibilityClass(result.compatibility);return`<article class="daily-result-item ${cls}"><div class="daily-result-number">${index+1}</div><div class="daily-result-content"><h3>${escapeHtml(question.prompt)}</h3><div class="daily-pair-answers"><div><small>${escapeHtml(settings.names[0])}</small><strong><b>${String.fromCharCode(65+result.leftAnswer)}</b>${escapeHtml(left)}</strong></div><div><small>${escapeHtml(settings.names[1])}</small><strong><b>${String.fromCharCode(65+result.rightAnswer)}</b>${escapeHtml(right)}</strong></div></div><span class="daily-match-label">${compatibilityLabel(result.compatibility)} · ${result.compatibility}%</span></div></article>`}).join('')}</div><div class="daily-summary-actions"><button class="button primary" onclick="showDailyStats()">Statystyki 14/30 dni</button><button class="button secondary" onclick="shareDailyResult()">Udostępnij wynik</button><button class="button tertiary" onclick="goHome()">Wróć na pulpit</button></div></section>`}
async function shareDailyResult(){const state=getDailyState(),meta=categoryMeta(state.category),text=`Między Nami — dzisiejsze dopasowanie: ${state.score}% (${meta.label}).`;try{if(navigator.share)await navigator.share({title:'Między Nami — nasz wynik',text});else{await navigator.clipboard.writeText(text);toast('Wynik skopiowany.')}}catch{}}

function showDailyStats(period){const daily=ensureDailyProfile();if(period&&DAILY_PERIODS.includes(String(period)))daily.period=String(period);ui.view='daily-stats';saveProfile();render()}
function renderDailyStats(){const daily=ensureDailyProfile(),period=daily.period||'14',stats=dailyStatsFor(period),all=completedEntries(),streak=dailyStreak(),max=Math.max(1,...Object.values(stats.categoryAverages)),last14=all.slice(-14),best=all.length?Math.max(...all.map(entry=>entry.score)):0;app.innerHTML=`<section class="panel wide daily-stats-panel"><div class="top-row"><button class="back-button" onclick="goHome()">← Pulpit</button><span class="chip">Historia lokalna</span></div><h1>Wasze dopasowanie</h1><p class="muted">Wyniki Codziennego Dopasowania są liczone osobno od zwykłych sesji gier.</p><div class="period-tabs">${[['7','7 dni'],['14','14 dni'],['30','30 dni'],['all','Całość']].map(([id,label])=>`<button class="${period===id?'active':''}" onclick="showDailyStats('${id}')">${label}</button>`).join('')}</div><div class="daily-stat-grid"><div><strong>${stats.entries.length?stats.average+'%':'—'}</strong><span>średnie dopasowanie</span></div><div><strong>${stats.entries.length}</strong><span>ukończonych dni w okresie</span></div><div><strong>${streak.current}</strong><span>obecna seria</span></div><div><strong>${best?best+'%':'—'}</strong><span>najlepszy dzień</span></div></div><h2>Ostatnie 14 wyników</h2>${last14.length?`<div class="daily-chart" aria-label="Wykres ostatnich wyników">${last14.map(entry=>`<div title="${escapeHtml(formatDailyDate(entry.date,true))}: ${entry.score}%"><span style="height:${Math.max(8,entry.score)}%"></span><small>${escapeHtml(formatDailyDate(entry.date,true).replace('.',''))}</small></div>`).join('')}</div>`:'<div class="empty">Pierwszy słupek pojawi się po ukończeniu dzisiejszego testu.</div>'}<h2>Dopasowanie według kategorii</h2>${Object.keys(stats.categoryAverages).length?`<div class="daily-category-bars">${Object.entries(stats.categoryAverages).sort((a,b)=>b[1]-a[1]).map(([id,value])=>{const meta=categoryMeta(id);return`<div><span>${meta.icon} ${escapeHtml(meta.label)}</span><i><b style="width:${value}%"></b></i><strong>${value}%</strong></div>`}).join('')}</div>`:'<div class="empty">Kategorie pojawią się wraz z kolejnymi dniami.</div>'}<div class="desktop-section-title"><div><h2>Historia dni</h2><p>Pełny wynik pozostaje zapisany na tym urządzeniu.</p></div></div>${all.length?`<div class="daily-history-list">${all.slice(-30).reverse().map(entry=>{const meta=categoryMeta(entry.category);return`<button onclick="openDailyHistory('${entry.date}')"><span class="history-icon" style="--daily-accent:${meta.accent}">${meta.icon}</span><span><strong>${escapeHtml(meta.label)}</strong><small>${escapeHtml(formatDailyDate(entry.date))}</small></span><b>${entry.score}%</b></button>`}).join('')}</div>`:'<div class="empty">Nie macie jeszcze ukończonych testów.</div>'}</section>`}
function openDailyHistory(key){const state=getDailyState(key,false);if(!state?.finishedAt)return;ensureDailyProfile().viewDate=key;ui.view='daily-history';render()}
function renderDailyHistory(){const key=ensureDailyProfile().viewDate,state=getDailyState(key,false);if(!state?.finishedAt){showDailyStats();return}const questions=questionList(state),meta=categoryMeta(state.category),[headline,description]=scoreLabel(state.score);app.innerHTML=`<section class="panel wide daily-panel" style="--daily-accent:${meta.accent}"><div class="top-row"><button class="back-button" onclick="showDailyStats()">← Statystyki</button><span class="chip">${escapeHtml(formatDailyDate(state.date))}</span></div><div class="history-result-head"><span>${meta.icon}</span><div><small>${escapeHtml(meta.label)}</small><h1>${state.score}% · ${escapeHtml(headline)}</h1><p>${escapeHtml(description)}</p></div></div><div class="daily-result-list">${questions.map((question,index)=>{const result=state.results[index];return`<article class="daily-result-item ${compatibilityClass(result.compatibility)}"><div class="daily-result-number">${index+1}</div><div class="daily-result-content"><h3>${escapeHtml(question.prompt)}</h3><div class="daily-pair-answers"><div><small>${escapeHtml(settings.names[0])}</small><strong><b>${String.fromCharCode(65+result.leftAnswer)}</b>${escapeHtml(question.answers[result.leftAnswer])}</strong></div><div><small>${escapeHtml(settings.names[1])}</small><strong><b>${String.fromCharCode(65+result.rightAnswer)}</b>${escapeHtml(question.answers[result.rightAnswer])}</strong></div></div><span class="daily-match-label">${compatibilityLabel(result.compatibility)} · ${result.compatibility}%</span></div></article>`}).join('')}</div></section>`}

function showPackHub(){ui.view='pack-hub';ui.modal=null;render()}
function renderPackHub(){app.innerHTML=`<section class="panel wide pack-hub"><div class="top-row"><button class="back-button" onclick="goHome()">← Pulpit</button><span class="chip">10 gotowych zestawów</span></div><h1>Pakiety tematyczne</h1><p class="muted">Klikasz i od razu rozpoczynasz gotową, zrównoważoną sesję.</p><div class="pack-hub-grid">${PACK_HUB.map((pack,index)=>`<button onclick="startPack('${pack.id}')" data-index="${String(index+1).padStart(2,'0')}"><span>${pack.icon}</span><div><strong>${escapeHtml(pack.title)}</strong><p>${escapeHtml(pack.text)}</p></div><i>Start →</i></button>`).join('')}</div></section>`}

const baseRenderStatsV06=renderStats;
renderStats=function(){const game=calculateStats(),daily=dailyStatsFor('14'),streak=dailyStreak(),categories={};for(const session of profile.sessions||[])for(const category of session.categories||[])categories[category]=(categories[category]||0)+1;const max=Math.max(1,...Object.values(categories));app.innerHTML=`<section class="panel wide"><div class="top-row"><button class="back-button" onclick="goHome()">← Pulpit</button><span class="chip">Wszystko na jednym ekranie</span></div><h1>Wasze statystyki</h1><p class="muted">Zwykłe sesje i Codzienne Dopasowanie są zapisywane lokalnie i mają osobne wyniki.</p><div class="stats-split"><button class="stats-feature daily-feature" onclick="showDailyStats()"><small>CODZIENNE DOPASOWANIE · 14 DNI</small><strong>${daily.entries.length?daily.average+'%':'—'}</strong><span>${daily.entries.length} ukończonych dni · seria ${streak.current}</span><i>Zobacz szczegóły →</i></button><div class="stats-feature"><small>ZWYKŁE GRY</small><strong>${game.matchRate||0}%</strong><span>${game.sessions} sesji · ${game.rounds} kart · ${game.shared} wspólnych punktów</span></div></div><h2>Najczęściej grane tematy</h2>${Object.keys(categories).length?`<div class="bar-list">${Object.entries(categories).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([category,count])=>`<div class="bar-row"><span>${CATEGORY_LABELS[category]||escapeHtml(category)}</span><div><i style="width:${Math.round(count/max*100)}%"></i></div><b>${count}</b></div>`).join('')}</div>`:'<div class="empty">Statystyki tematów pojawią się po pierwszej sesji.</div>'}<h2>Ostatnie sesje gier</h2>${profile.sessions.length?`<div class="list">${profile.sessions.slice(-10).reverse().map(session=>`<div class="list-item"><div><strong>${escapeHtml(modeMeta(session.mode).title)}</strong><p>${formatDate(session.finishedAt)} • ${session.rounds} kart • ${session.matchRate}% zgodności</p></div><span class="chip">${session.shared} wsp.</span></div>`).join('')}</div>`:'<div class="empty">Nie macie jeszcze ukończonej zwykłej sesji.</div>'}</section>`}

const previousRenderV06=render;
render=function(){
  ensureDailyProfile();
  if(ui.view==='daily-intro')renderDailyIntro();
  else if(ui.view==='daily-play')renderDailyPlay();
  else if(ui.view==='daily-handoff')renderDailyHandoff();
  else if(ui.view==='daily-summary')renderDailySummary();
  else if(ui.view==='daily-stats')renderDailyStats();
  else if(ui.view==='daily-history')renderDailyHistory();
  else if(ui.view==='pack-hub')renderPackHub();
  else previousRenderV06();
  if(['daily-intro','daily-play','daily-handoff','daily-summary','daily-stats','daily-history','pack-hub'].includes(ui.view)){renderModal();window.scrollTo({top:0,behavior:'smooth'})}
  document.title=ui.view.startsWith('daily-')?'Codzienne Dopasowanie — Między Nami':ui.view==='pack-hub'?'Pakiety — Między Nami':document.title;
  const badge=document.querySelector('.version-badge');if(badge)badge.textContent=`v${V06_VERSION}`;
  const heroBadge=document.querySelector('.hero .eyebrow');if(heroBadge)heroBadge.textContent=`${LIBRARY.length} KART • 11 APLIKACJI • TRYB DZIENNY`;
};

const previousRenderModalV06=renderModal;
renderModal=function(){previousRenderModalV06();if(ui.modal==='main-menu'){const list=document.querySelector('.menu-list');if(list&&!list.querySelector('[data-v06-daily]'))list.insertAdjacentHTML('afterbegin',`<button class="menu-item" data-v06-daily onclick="openDailyMatch()">Codzienne Dopasowanie<span>Dzisiejsze 5 pytań i wspólny wynik</span></button><button class="menu-item" onclick="showDailyStats()">Historia dopasowania<span>Wyniki 7, 14 i 30 dni</span></button><button class="menu-item" onclick="showPackHub()">Pakiety tematyczne<span>Gotowe sesje uruchamiane jednym kliknięciem</span></button>`)} };

Object.assign(window,{openDailyMatch,startDailyMatch,dailyChoose,dailyPrevious,dailyExit,dailyAcceptHandoff,shareDailyResult,showDailyStats,openDailyHistory,showPackHub,MN_DAILY_ENGINE:{dailyDefinition,questionCompatibility,questionList,categoryMeta,compatibilityLabel,compatibilityClass,scoreLabel,formatDailyDate,localDateKey,DAILY_BY_ID,DAILY_PAYLOAD}});
ensureDailyProfile();saveProfile();
const launchParams=new URLSearchParams(location.search);
if(launchParams.get('daily')==='1')ui.view=getDailyState().finishedAt?'daily-summary':'daily-intro';
render();
})();
